# Generated by Django 4.2.6 on 2023-11-04 15:02

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('description', models.TextField()),
                ('publication_date', models.DateField()),
                ('cover', models.ImageField(upload_to=books.models.book_path)),
            ],
        ),
    ]
