# Generated by Django 4.2.6 on 2023-10-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
